name       : networkmanager-strongswan
version    : 1.6.0
release    : 4
source     :
    - https://download.strongswan.org/NetworkManager/NetworkManager-strongswan-1.6.0.tar.bz2 : 6dbc80f6a09ba0cf6104a31784959780414dd77165e2963acd6657c28c2544c2
license    : GPL-2.0-or-later
component  : network.base
summary    : strongSwan support for NetworkManager
description: |
    strongSwan IPsec VPN plugin for NetworkManager which provides support for EAP, PSK and certificate authentication.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssl)
rundeps    :
    - strongswan
setup      : |
    %configure --sysconfdir=/etc \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --with-charon=/usr/lib64/ipsec/charon-nm \
               --without-libnm-glib \
               --disable-static
build      : |
    %make
install    : |
    %make_install
