name       : networkmanager-strongswan
version    : 1.5.0
release    : 1
source     :
    - https://download.strongswan.org/NetworkManager/NetworkManager-strongswan-1.5.0.tar.bz2 : c4ff0ec330de048ce98a9eb87912c863229993cc5d20db82efce9c1df28ed0f4
license    : GPL-2.0-or-later
component  : network.base
summary    : strongSwan support for NetworkManager
description: |
    strongSwan IPsec VPN plugin for NetworkManager which provides support for EAP, PSK and certificate authentication.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssl)
rundeps:
    - strongswan
setup: |
    %configure --sysconfdir=/etc \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --with-charon=/usr/lib64/ipsec/charon-nm \
               --without-libnm-glib \
               --disable-static
build      : |
    %make
install    : |
    %make_install
